site_url: https://dynamic-puppy-9c60ac.netlify.app/
locale: "ja"
backend:
  # ローカルでテストする場合はtest-repoに書き換える
  # see: https://decapcms.org/docs/nextjs/
  name: git-gateway
  branch: main

media_folder: static/images/upload
public_folder: /images/upload

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{fields.slug}}"
    path: "{{year}}/{{month}}/{{slug}}"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - { label: "Body", name: "body", widget: "markdown" }
